### ISSUE TITLE
Issue with the example data 

### ISSUE THREAD

**Issue by lakshitadodeja** [kpertsch/bridge_rlds_builder#2]
Hi, 
Thank you for providing this repo for rlds data conversion !
I was trying to following the basic commands in read me and I am getting this issue - 

command `CUDA_VISIBLE_DEVICE=0 tfds build`

error - 
```
INFO[build.py]: Loading dataset  from path: /home/dodeja/Documents/comps/bridge_rlds_builder/bridge_dataset/bridge_dataset_dataset_builder.py
2024-02-23 15:49:54.313814: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-02-23 15:49:54.334164: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-02-23 15:49:54.334209: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-02-23 15:49:54.334935: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-02-23 15:49:54.338585: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-02-23 15:49:54.625308: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:901] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2024-02-23 15:49:54.644855: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:901] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2024-02-23 15:49:54.644976: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:901] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2024-02-23 15:49:54.705329: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
2024-02-23 15:49:54.986711: W external/local_tsl/tsl/platform/cloud/google_auth_provider.cc:184] All attempts to get a Google authentication bearer token failed, returning an empty token. Retrieving token from files failed with "NOT_FOUND: Could not locate the credentials file.". Retrieving token from GCE failed with "FAILED_PRECONDITION: Error executing an HTTP request: libcurl code 6 meaning 'Couldn't resolve host name', error details: Could not resolve host: metadata.google.internal".
INFO[build.py]: download_and_prepare for dataset bridge_dataset/1.0.0...
INFO[dataset_builder.py]: Generating dataset bridge_dataset (/home/dodeja/tensorflow_datasets/bridge_dataset/1.0.0)
Downloading and preparing dataset Unknown size (download: Unknown size, generated: Unknown size, total: Unknown size) to /home/dodeja/tensorflow_datasets/bridge_dataset/1.0.0...
Converting 0 training and 0 validation files.
Converting 0 training and 0 validation files.
Generating splits...:   0%|                          | 0/2 [00:00<?, ? splits/s]Generating with 40 workers!
INFO[resolver.py]: Using /tmp/tfhub_modules to cache modules.                   
Generating splits...:   0%|                          | 0/2 [00:00<?, ? splits/s2024-02-23 15:49:55.786014: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:901] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2024-02-23 15:49:55.786133: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:901] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2024-02-23 15:49:55.786181: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:901] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2024-02-23 15:49:55.832159: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:901] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2024-02-23 15:49:55.832265: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:901] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2024-02-23 15:49:55.832329: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:901] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2024-02-23 15:49:55.832379: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 1123 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 4080 Laptop GPU, pci bus id: 0000:01:00.0, compute capability: 8.9
INFO[load.py]: Fingerprint not found. Saved model loading will continue.        
INFO[load.py]: path_and_singleprint metric could not be logged. Saved model loading will continue.                                                              
Generating splits...:   0%|                          | 0/2 [00:05<?, ? splits/sWriting conversion results...                                                    
Finishing split conversion...
Traceback (most recent call last):                                              
  File "/home/dodeja/miniconda3/envs/rlds_env/bin/tfds", line 8, in <module>
    sys.exit(launch_cli())
  File "/home/dodeja/miniconda3/envs/rlds_env/lib/python3.9/site-packages/tensorflow_datasets/scripts/cli/main.py", line 109, in launch_cli
    app.run(main, flags_parser=_parse_flags)
  File "/home/dodeja/miniconda3/envs/rlds_env/lib/python3.9/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/home/dodeja/miniconda3/envs/rlds_env/lib/python3.9/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/home/dodeja/miniconda3/envs/rlds_env/lib/python3.9/site-packages/tensorflow_datasets/scripts/cli/main.py", line 104, in main
    args.subparser_fn(args)
  File "/home/dodeja/miniconda3/envs/rlds_env/lib/python3.9/site-packages/tensorflow_datasets/scripts/cli/build.py", line 282, in _build_datasets
    _download_and_prepare(args, builder)
  File "/home/dodeja/miniconda3/envs/rlds_env/lib/python3.9/site-packages/tensorflow_datasets/scripts/cli/build.py", line 518, in _download_and_prepare
    builder.download_and_prepare(
  File "/home/dodeja/miniconda3/envs/rlds_env/lib/python3.9/site-packages/tensorflow_datasets/core/logging/__init__.py", line 169, in __call__
    return function(*args, **kwargs)
  File "/home/dodeja/miniconda3/envs/rlds_env/lib/python3.9/site-packages/tensorflow_datasets/core/dataset_builder.py", line 646, in download_and_prepare
    self._download_and_prepare(
  File "/home/dodeja/Documents/comps/bridge_rlds_builder/bridge_dataset/conversion_utils.py", line 89, in _download_and_prepare
    future = split_builder.submit_split_generation(
  File "/home/dodeja/miniconda3/envs/rlds_env/lib/python3.9/site-packages/tensorflow_datasets/core/split_builder.py", line 341, in submit_split_generation
    return self._build_from_generator(**build_kwargs)
  File "/home/dodeja/Documents/comps/bridge_rlds_builder/bridge_dataset/conversion_utils.py", line 205, in _build_from_generator
    shard_lengths, total_size = writer.finalize()
  File "/home/dodeja/miniconda3/envs/rlds_env/lib/python3.9/site-packages/tensorflow_datasets/core/writer.py", line 243, in finalize
    shard_specs = _get_shard_specs(
  File "/home/dodeja/miniconda3/envs/rlds_env/lib/python3.9/site-packages/tensorflow_datasets/core/writer.py", line 111, in _get_shard_specs
    shard_boundaries = _get_shard_boundaries(num_examples, num_shards)
  File "/home/dodeja/miniconda3/envs/rlds_env/lib/python3.9/site-packages/tensorflow_datasets/core/writer.py", line 142, in _get_shard_boundaries
    raise AssertionError("No examples were yielded.")
AssertionError: No examples were yielded.

```

**Comment by kpertsch** [comment]
the error indicates that no examples were produced -- maybe you can add a print statement below this line and make sure it actually produces samples: https://github.com/kpertsch/bridge_rlds_builder/blob/f0d16c5a8384c1476aa1c274a9aef3a5f76cbada/bridge_dataset/bridge_dataset_dataset_builder.py#L76

Also note how your printouts say "Converting 0 training and 0 validation files." -- this shows that the glob command does not end up finding any files, so you need to correct the file path for it.

Finally please note that the README was not adapted after forking from https://github.com/kpertsch/rlds_dataset_builder so it is not up-to-date with Bridge data conversion if that is what you are trying to do

**Comment by lakshitadodeja** [comment]
I didn't see the original repo, it worked with that ! 
Thank you !
